name: Audit

on:
  push:
  schedule:
    - cron: "40 10 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  audit:
    uses: inrupt/javascript-style-configs/.github/workflows/reusable-audit.yml@main
    secrets:
      WEBHOOK_E2E_FAILURE: ${{ secrets.WEBHOOK_E2E_FAILURE }}
