name: Audit

on:
  push:
  schedule:
    - cron: "40 10 * * *"

jobs:
    audit:
      uses: inrupt/javascript-style-configs/.github/workflows/reusable-audit.yml@eb439749b5c3e017c26577ff34a7d16734f13d0a
      secrets:
        WEBHOOK_E2E_FAILURE: ${{ secrets.WEBHOOK_E2E_FAILURE }}
